name: slide_app
description: "A new Flutter project."

# يمنع نشر الحزمة على pub.dev
publish_to: 'none'

# رقم الإصدار والبناء للتطبيق
version: 1.0.0+1

# بيئة العمل المطلوبة
environment:
  sdk: ^3.7.2

# الحزم الأساسية المطلوبة للتطبيق
dependencies:
  flutter:
    sdk: flutter

  # أيقونات نظام iOS
  cupertino_icons: ^1.0.8

  # لالتقاط الصور من الكاميرا أو المعرض
  image_picker: ^1.1.0

  # أيقونات جاهزة بتصميم جميل
  line_awesome_flutter: ^2.0.0

# حزم التطوير والاختبار
dev_dependencies:
  flutter_test:
    sdk: flutter

  # قواعد تنبيه لتحسين جودة الكود
  flutter_lints: ^5.0.0

# إعدادات خاصة بـ Flutter
flutter:
  uses-material-design: true

  # إضافة الصور من مجلد assets/images
  assets:
    - assets/images/icons8-user-96.png
