// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27el5ijpGsQ778Q3xNTEN3_XNXqqyafU',
    appId: '1:3726596232:web:c5dd94ee0d9bab0e92673d',
    messagingSenderId: '3726596232',
    projectId: 'slide-app-58788',
    authDomain: 'slide-app-58788.firebaseapp.com',
    storageBucket: 'slide-app-58788.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwlAVdBylhJg8KHa85RxLnm8eu8FpROw',
    appId: '1:3726596232:android:9b3481b70b76630692673d',
    messagingSenderId: '3726596232',
    projectId: 'slide-app-58788',
    storageBucket: 'slide-app-58788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQFj_bFFemCzN8S0TPvgsahNh6PJHUTJQ',
    appId: '1:3726596232:ios:27ba02a348889bbe92673d',
    messagingSenderId: '3726596232',
    projectId: 'slide-app-58788',
    storageBucket: 'slide-app-58788.firebasestorage.app',
    iosBundleId: 'com.example.slideTeamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQFj_bFFemCzN8S0TPvgsahNh6PJHUTJQ',
    appId: '1:3726596232:ios:27ba02a348889bbe92673d',
    messagingSenderId: '3726596232',
    projectId: 'slide-app-58788',
    storageBucket: 'slide-app-58788.firebasestorage.app',
    iosBundleId: 'com.example.slideTeamProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD27el5ijpGsQ778Q3xNTEN3_XNXqqyafU',
    appId: '1:3726596232:web:90160607e696d59192673d',
    messagingSenderId: '3726596232',
    projectId: 'slide-app-58788',
    authDomain: 'slide-app-58788.firebaseapp.com',
    storageBucket: 'slide-app-58788.firebasestorage.app',
  );
}
